version: '3'
services:
    auth-server:
        image: bitnami/openldap:2
        container_name: openldap-auth-server
        volumes:
          - ./imports:/ldifs
        ports:
            - "1389:1389"
            - "1636:1636"
        environment:
            - LDAP_ADMIN_USERNAME=admin
            - LDAP_ADMIN_PASSWORD=1234
            - LDAP_ROOT=dc=bernardomg,dc=com
    ws:
        depends_on:
            - auth-server
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        container_name: ldap-ws
        ports:
            - "8080:8080"
            - "8000:8000"
        environment:
            # Auth server
            - spring.ldap.url=ldap://host.docker.internal:1389
            - spring.ldap.base=dc=bernardomg,dc=com
            - spring.ldap.username=uid=user,ou=people
            - spring.ldap.password=1234
